
# Homework 0


## Vecitorization

### sum products

In [1]:
import numpy


def vectorize_sumproducts():
    """
     Takes two 1-dimensional arrays and sums the products of all the pairs.
    :return:
    """
    print("求向量a中每个元素与向量b中对应元素乘积之和")
    print('输入;')
    a, b = input().split('] [')
    a = list(map(float, a.strip('[').split()))
    b = list(map(float, b.strip('] ').split()))
    print("输出;")
    return numpy.sum(numpy.multiply(a, b))

print(vectorize_sumproducts())


求向量a中每个元素与向量b中对应元素乘积之和
输入;
[1 2 3 4] [1 2 3 4]
输出;
30.0


### Vectorize_Relu

In [2]:
def vectorize_Relu():
    """
    Takes one 2-dimensional array and apply the relu function on all the values of the array.
    :return:
    """
    a = numpy.random.randn(5, 5)
    # Here are two ways to do Relu
    loc = numpy.where(a > 0, a, 0)
    loc1 = numpy.maximum(a, 0)
    print(loc)
    print(loc1)

    
vectorize_Relu()

[[0.12014268 0.04807053 0.11371428 1.04689747 0.73259511]
 [0.         0.17910703 0.27541831 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.73085849 0.        ]
 [0.         0.         0.14753589 1.32250646 0.15671883]]
[[0.12014268 0.04807053 0.11371428 1.04689747 0.73259511]
 [0.         0.17910703 0.27541831 0.         0.        ]
 [0.         0.         0.         0.         0.        ]
 [0.         0.         0.         1.73085849 0.        ]
 [0.         0.         0.14753589 1.32250646 0.15671883]]


### vectorize_PrimeRelu

In [3]:
def vectorize_PrimeRelu():
    """
    Takes one 2-dimensional array and apply the derivative of relu function on all the values of the array.
    :return:
    """
    a = numpy.random.randn(5, 5)
    a = numpy.where(a < 0, 0, 1)
    print(a)

    
vectorize_PrimeRelu()

[[1 1 1 0 0]
 [0 1 1 1 1]
 [1 1 1 1 0]
 [0 0 0 1 0]
 [1 0 0 1 1]]


## Variable Length

### Slice_fixed_point

In [5]:
def Slice_fixed_point(data, m, n):
    """
    Takes one 3-dimensional array with the starting position and the length of the output instances.
    Your task is to slice the instances from the same starting position for the given length.
    :return:
    """
    result = []
    for i in data:
        temp = []
        for j in range(m, m + n):
            if j < len(i):
                temp.append(i[j])
            else:
                temp.append('')
        result.append(temp)
    return result

data = [
        ['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'],
        ['u1l1', 'u1l2', 'u1l3'],
        ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'],
        ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']
    ]
result = Slice_fixed_point(data, 1, 2)
print(result)

[['u0l1', 'u0l2'], ['u1l2', 'u1l3'], ['u2l1', 'u2l2'], ['u3l1', 'u3l2']]


### slice_last_point

In [6]:
def slice_last_point(data, lastPos=0):
    """
     Takes one 3-dimensional array with the length of the output instances.
     Your task is to keeping only the l last points for each instances in the dataset.
    :return:
    """
    result = []
    for i in data:
        result.append(i[-1 - lastPos:-1])
    return result
    
data = [
        ['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'],
        ['u1l1', 'u1l2', 'u1l3'],
        ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'],
        ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']
    ]
result = slice_last_point(data)
print(data)

[['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'], ['u1l1', 'u1l2', 'u1l3'], ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'], ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']]


### slice_random_point

In [11]:
def slice_random_point(data, length):
    """
     Takes one 3-dimensional  array  with  the  length  of the output instances.
     Your task is to slice the instances from a random point in each of the utterances with the given length.
     Please use function numpy.random.randint for generating the starting position.
    :return:
    """
    result=[]
    for i in data:
        loc = numpy.random.randint(0,len(i),length)
        temp=[]
        for j in loc:
            temp.append(i[j])
        result.append(temp)

    return result

data = [
        ['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'],
        ['u1l1', 'u1l2', 'u1l3'],
        ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'],
        ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']
    ]
result = slice_random_point(data, 2)
print(result)

[4 2]
[0 0]
[4 0]
[1 2]
[['u0l4', 'u0l2'], ['u1l1', 'u1l1'], ['u2l4', 'u2l0'], ['u3l1', 'u3l2']]


### pad_pattern_end

In [22]:
def pad_pattern_end(data):
    """
    Takes one 3-dimensional array.
    Your task is to pad the instances from the end position as shown in the example below.
    That is, you need to pad the reflection of the utterance mirrored along the edge of the array.
    :return:
    """
    result=[]
    max_len = max([len(i) for i in data])
    for i in data:
        if len(i) < max_len:
            i.extend(i[-1:(len(i)-max_len-1):-1])
            result.append(i)
        else:
             result.append(i)   
    return result
    
data = [
        ['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'],
        ['u1l1', 'u1l2', 'u1l3'],
        ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'],
        ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']
    ]
result = pad_pattern_end(data)
print(result)

[['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4', 'u0l4'], ['u1l1', 'u1l2', 'u1l3', 'u1l3', 'u1l2', 'u1l1'], ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'], ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4', 'u3l4']]


### pad_constant_central

In [24]:
def pad_constant_central(data):
    """
     Takes one 3-dimensional array with the constant value of padding.
     Your task is to pad the instances with the given constant value while maintaining the array at the center of the padding.
    :return:
    """
    result=[]
    max_len = max([len(i) for i in data])
    for i in data:
        if len(i) < max_len:
            i.extend(['cval']*(max_len-len(i)))
            result.append(i)
        else:
             result.append(i)   
    return result
    
data = [
        ['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4'],
        ['u1l1', 'u1l2', 'u1l3'],
        ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'],
        ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4']
    ]
result = pad_constant_central(data)
print(result)   


[['u0l0', 'u0l1', 'u0l2', 'u0l3', 'u0l4', 'cval'], ['u1l1', 'u1l2', 'u1l3', 'cval', 'cval', 'cval'], ['u2l0', 'u2l1', 'u2l2', 'u2l3', 'u2l4', 'u2l5'], ['u3l0', 'u3l1', 'u3l2', 'u3l3', 'u3l4', 'cval']]


## Numpy and PyTorch Conversion

### def numpy2tensor

In [25]:
import torch
import numpy as np
def numpy2tensor(ndarray):
    """
    Takes a numpy ndarray and converts it to a PyTorch tensor.
    Function torch.tensor is one of the simple ways to implement it but please do not use it this time.
    :return:
    """
    return torch.from_numpy(ndarray)

### tensor2numpy

In [26]:
def tensor2numpy(tensor):
    """
    Takes a PyTorch tensor and converts it to a numpy ndarray.
    :return:
    """
    return tensor.numpy()

### Tensor_Sumproducts

In [28]:
def Tensor_Sumproducts(tensor1, tensor2):
    """
    you are to implement the function tensor sumproducts that takes two tensors as input.
    returns the sum of the element-wise products of the two tensors.
    :return:
    """
    array1 = tensor2numpy(tensor1)
    array2 = tensor2numpy(tensor2)
    return np.sum(np.multiply(array1, array2))

### Tensor_Relu

In [29]:
def Tensor_Relu(tensor):
    """
    Takes one 2-dimensional tensor and apply the relu function on all the values of the tensor.
    :return:
    """
    array = tensor2numpy(tensor)
    loc = numpy.where(array > 0, array, 0)
    new_tensor = numpy2tensor(loc)
    return new_tensor

### Tensor_Relu_prime

In [30]:
def Tensor_Relu_prime(tensor):
    """
    Takes one 2-dimensional tensor and apply the derivative of relu function on all the values of the tensor.
    :return:
    """
    array = tensor2numpy(tensor)
    array = numpy.where(array < 0, 0, 1)
    new_tensor = numpy2tensor(array)
    return new_tensor